### ISSUE TITLE
Developed a simillar program but getting access denied while scraping image links

### ISSUE THREAD

**Issue by RootEncrypter** [Daemitrious/DaeManga#1]
hey i developed a simillar program using requests . i am using cookie to get access the page, i am able to get the image links but when i tried to download the image content by sending a request i get a access denied and unable to scrape the image. i also added user agent and cookies , how di you get past through this ? @Daemitrious

**Comment by Daemitrious** [comment]
>  i get a access denied and unable to scrape the image.

could you send a snippet of your code?  Could you also send the permission error you are getting?

also thanks a bunch for checking this out!

**Comment by Daemitrious** [comment]
I downloaded each image by grabbing the direct link of the image
e.g: (https://xy-10-j.mangapark.net/50/ef/5c4ac9b33a2e574b6077fe05/04_153208_757_1200.jpeg)

To grab these, at least in "manganelos", there is a huge list of each page for the selected chapter.  Each is separated by a comma so you have to make your own list:
```python
links = strip(soup.find("p", id="arraydata")).split(",")
```
`strip` is a custom function that just takes the `text.strip()` method from `bs4`:
```python
def strip(string):  # "text.strip()" `string` [function]
    return string.text.strip()
```
|   , how di you get past through this ? @Daemitrious

To answer your question,

Basically, I used `requests` (`get`) to grab the contents of the specified image
```python
res = get(cLink, stream=True)
```

`cLink` is set to `links[pDownloaded]` where  `links` is a list of every direct iink to each image in the chapter which is being iterated through with `pDownloaded` which is the current page of the current chapter being downloaded at that time

and i would use the content of `res` to write that to the new directory all in accordance to the manga and chapter name
```python
with open(f"{dPath}\\Page {str(pDownloaded)}.jpeg", "wb") as f:  # Write the content of `pDownloaded` to `dPath`
    f.write(res.content)
```
`dPath` is the download path

I'm not using cookies or anything of the sort.

**Comment by RootEncrypter** [comment]
hey are you scraping from mangapark? i though you were scraping from "https://manganelo.com/chapter/read_one_piece_manga_online_free4/chapter_967"
Try this website, you will get an access denied while requesting the image.

my code for downloading image is 
` img_data = requests.get(page_links).content`
`with open(f"{str(page_no)}.jpg", 'wb') as handler:`
`  handler.write(img_data)`

here  "page_links" is an imagelink eg : https://bu3.mkklcdnbuv1.com/mangakakalot/o1/one_piece/chapter_967_rogers_adventure/6.jpg

check it out and tell me, @Daemitrious

**Comment by RootEncrypter** [comment]
![now](https://user-images.githubusercontent.com/62509239/95480555-a5294380-09a9-11eb-9589-a4e1c8967ab6.JPG)

This is the access denied

**Comment by Daemitrious** [comment]
Not sure where you're getting "https://manganelo.com/chapter/read_one_piece_manga_online_free4/chapter_967" from but if you just search for "one piece" then select "one piece" then "chapter 967" it will give you "http://manganelos.com/one-piece-chapter-967#1" which is the native url for this domain.

"http://manganelos.com/" - This is the correct website.  @RootEncrypter 
![image](https://user-images.githubusercontent.com/62043858/95481555-1e4d7a00-095b-11eb-8986-7e8316cd41a2.png)  should look like this

**Comment by RootEncrypter** [comment]
haha i figured it out , the website i tried to scrape is "manganelo.com" and the website you are scraping is "manganelos.com"
. "manganelo.com" has a cloudflare protection,do check out that website. cheers

**Comment by Daemitrious** [comment]
hahahha yeah there are several versions out there

Are you making your own downloader of it for practice? @RootEncrypter

**Comment by RootEncrypter** [comment]
I suggest you to use cookies+requests because it will be much faster and optimal. I developed a telegram bot to download comics and manga, if you want to discuss regarding this or see the code hit me up on Discord : ShaunnyBoi#0380 or telegram : @badTrojan.

**Comment by Daemitrious** [comment]
okay cool.  i added you on discord.  I am Daemitrious
